### PR TITLE
Loader for KWD files from open-ehys

### PR DESCRIPTION
**Pull request by mmyros**
Hello, this package looks very nice, I'd love to try this on my data. I changed loader in main.py and highpass filter in core.py to work with KWD files from open-ehys. KWD files have a different orientation than the code expects, so I had to modify WMLDR so that dimensions are sane. Of course, this is just a hack.

Transposing the h5py array is not really an option, since that would put the entire dataset in memory.
I think this problem is propagated to SimpleStreamer as well, since after the filtering is completed,
my memory fills up. Could you help? Thanks!

### CODE REVIEW

**Comment by mspacek** [comment]
Hello! Your timing is excellent. I just added support for .dat files, which also come out of the cortexlab, and are often exported to for interoperability. I think the underlying raw data inside of a .kwd file is just a transposed .dat file (i.e., row major instead of column major), but I only glanced at the spec very briefly:

https://github.com/klusta-team/kwiklib/wiki/Kwik-format#kwd

The way you're currently doing it, by using a `SimpleStream`, means the whole thing is loaded into memory  at once, which is very inefficient.`dat.File` and its associated `stream.DATStream` use `numpy.memmap()`, which is much more efficient. I'd suggest making a `kwd.py` module with a `kwd.File` object that inherits from `dat.File`, and modifies some of the attributes and methods, in the same way that `nsx.File` does. The `kwd.DataPacket` should probably call `numpy.memmap()` with the `order='C'` argument to make it row major, instead of `order='F'` which assumes column major. Then, you also need to make a `stream.KWDStream` that then uses the `kwd.File` object.

Seems quite silly to me that they made it row major. You normally want access to time slices across all channels, not channel slices across all time. Oh well.

Hope that helps. Let me know if you get stuck!

**Comment by mmyros** [comment]
Nice! I might just use .dat, I already convert to them to use spyking-circus. One question, what is the json file? Could you share an example of one?

**Comment by mspacek** [comment]
Let me know if it works for you. If you get .kwd support in decent shape, please resubmit!

**Comment by mmyros** [comment]
Working well for me with the module [openephys](https://github.com/kylerbrown/openephys/tree/master/openephys) from kylerbrown. Compared with phy, spyke brings me much closer to the data, and makes it much easier to make sure there is no junk. Realignment is also great to have on demand. 

It would be nice to have a way to do detection in command line, perhaps you have scripts for something like this? Also, I miss auto-updating autocorrelations and cross-correlations from phy - having to click my way through plotting them for each cluster can get tiresome. I see though that the TODO list is very long, so perhaps you already have this planned. Thanks for making this available!

**Comment by mspacek** [comment]
Thanks Max, that's great to hear!

No, there's no command-line functionality for spike detection. I suppose it could be added, with the default setting being the same as the GUI defaults. I don't have any particular use for it though. In fact, we're moving towards using kilosort for the initial clustering, which is certainly better than the initial split by maxchan. I convert the various kilosort .npy result files to a single .events.zip file (using File->Convert in spyke), which is just a .zip file of 3 numpy arrays: spike times, channel IDs, and cluster IDs. After opening the stream (like a .dat or an .ns6, whatever kilosort was run on) and then opening the .events.zip file, spyke extracts the waveforms from the stream, does spatial localization on each spike, and assigns them kilosort's cluster IDs. From then on you can view and curate clusters the same way as if spyke's own detection algorithm and initial split steps had been run on the stream. You can also save the session to a .sort file. Aren't you using spyking-circus for detection anyway?

I find autocorrs and xcorrs way overrated, especially when it comes to low firing rate cells. That's why correlograms are not very prominent in the interface. They can tell you if your clustering is terrible, but not if it's any good, or how to improve it. They can also provide a false sense of security. I go through the reasoning in my [thesis](http://mspacek.github.io/mspacek_thesis.pdf) (sections 3.11 and 3.13.4). Needs to be published!

That said, you're certainly more than welcome to make improvements!

**Comment by mmyros** [comment]
Well, I considered switching to spyke detection primarily for its wavelet filtering function. However, I lifted your wavelet function into spyking circus, do you mind? Of course, I put in a link to this repo. 

I ran the pipeline you suggested, and it seemed to have worked reasonably well, but I'm not sure that it will scale. I had 3.5 mln spikes from 32 channels and ran halfway into swap on my 12GB ram machine. I did not time the process, but it took something like 15 minutes. That's workable, but will be tough when going to multi-hour, 64-channel or more recordings. Any tips for slimming things down in terms of memory footprint?

One more question, do you by any chance have  a shortcut for finding a given spike in the raw data window?

Thanks!

**Comment by mspacek** [comment]
Sorry for the delay, I'm not getting GitHub notifications for some reason.

Of course I don't mind! The WMLDR() function is, I think, straight out of the description in the Wiltschko2008 paper. Pretty simple. Unfortunately, as I mention somewhere in the comments, it doesn't seem to completely get rid of some low frequencies. If you switch to WMLDR in the Filtering menu and then scroll the raw data slowly, you'll notice some slow wobbling. Not sure how to fix it. It might just be some inherent issue with WMLDR. So, I'm sticking with the standard Butterworth filter for now for that reason, and also because my spike detection assumes both a positive and negative peak in each spike, which is actually an artifact of the Butterworth filter. If I switch to WMLDR, I'd have to change my detection algorithm as well.

By the way, after seeing it mentioned in the kilosort paper, I added correlated noise removal (CAR, common average referencing) by subtracting the median of all the channels from each channel. Works great on our awake mouse data, and doesn't decrease spike amplitudes (unlike the mean).

Are you talking about the memory footprint of spyke when importing results from kilosort? Once detection is complete, the memory footprint is almost completely a function of the number of spikes detected, the number of channels per spike, the width of the time window around each spike, and the (re)sampling rate. At the moment, I'm working with about 5 million spikes, ~13 channels per spike, 2 ms time window per spike, and 60 kHz. Each spike comes to about 3 kB, for a total of about 15 GB of memory. 12 GB of RAM is not a lot. For heavy duty spike sorting, it's good to have at least 32 GB. You definitely want to avoid having to use swap.

All of this detected waveform data resides in the .wave file, which is entirely loaded into memory using `np.load()` and accessed via `Sort.wavedata`. It might be possible to memmap the file instead of loading it entirely into RAM. `np.load()` has a flag for that (`mmap_mode=c`). I might give it a try and see if everything still works. Resaving shifted waveforms to the .wave file on demand might be problematic...

To find a given spike in the raw data, just double-click the spike in the sorted or unsorted spike lists (lower two list widgets in the sort window).

**Comment by mmyros** [comment]
No worries! For low frequencies, have you considered some sort of
detrending like local linear regression? I occasionally have some DC
offsets that even Butterworth does not handle particularly well. I am
thinking of trying that. Also, I think the channels with offsets might mess
up other, good channels if I simply use CAR.

Currently, I am doing spyking circus with converting step, deleting junk
templates using their merging gui, renaming spike-templates.npy to
spike-clusters.npy, then convert kilosort to spyke. I think memmaping
should help future proof this somewhat. Maybe I can try it too one of these
days.

Thanks for the responses!

**Comment by mspacek** [comment]
Yeah, I don't have anything that specifically looks for and removes DC offsets. Butterworth seems to do a good enough job on our mouse data. The cat data I worked with during my PhD was already analog filtered, so no digital filtering was required to remove the LFP. I think my former supervisor, Nick Swindale, has some kind of a DC offset removal in his Windows+Fortran implementation called [SpikeSorter](http://www.swindale.ecc.ubc.ca/SpikeSorter). I think it pretty much just subtracts off, for each channel, the mean or median voltage across all timepoints.

Don't think I've ever even heard of local linear regression! The result looks nice on wikipedia. There's so many of these methods, it's hard to keep them straight in my head.

Strangely, it seems kilosort generates both a `spike_templates.pny` **and** a `spike_clusters.npy` file, and their contents are identical. Maybe that's an oversight, or some backward compatibility thing in kilosort. I happened to choose the `spike_clusters.npy` file in the conversion step, but that could be changed. I've opened up an issue [here](https://github.com/cortex-lab/KiloSort/issues/63).

I've added memmapping the .wave file to the long TODO list. Maybe I'll look at it in the near future, but I worry about silent bugs that might not crop up until after a lot of curation has already been done.

**Pull request closed without merging**
